export const ROUTES = {
  LOGIN: "/login",
  REGISTER: "/register",
  EDITPROFILE: "/editProfile",
  HOMEPAGE: "/",
  ADDBLOG: "/addblog",
  DETAILFLIGHT: "/detailflight/:id",
  LISTFLIGHT: "/listfilght",
  ACTIVATION: "/auth/active-email/:activation_token",
  DETAILPRODUCT: "/detail-product",
  DETAIL: "/detail/:id",
  CART: "/cart",
  PRODUCTTYPE: "/product-type/",
  ACCOUNT: "/account",
};
